name: Auto Deploy to cPanel Hosting

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync to Hosting
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync Core Laravel to /home/agrm6137/ggi
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ggi/
          security: loose
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/public/**
            deploy-manual.sh
            .cpanel.yml

      - name: 🌐 Sync Public Assets to /public_html/guritaglobal.com
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: public_html/guritaglobal.com/
          security: loose
          log-level: verbose
          exclude: |
            storage
            index.production.php
